package repository

import (
	"context"
	"distributed-queue/pkg/redis/metrics"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

var (
	ErrDuplicateJob    = errors.New("job execution skipped: already completed")
	ErrJobAlreadyOwned = errors.New("job execution skipped: another worker already owns this job")
	// ErrJobNotFound means TryStartJob was called for a taskID with no
	// corresponding processed_jobs row. Under this system's design that
	// should never happen — every task is created in Postgres via CreateJob
	// BEFORE its ID is ever pushed onto the Redis queue — so seeing this
	// error means something enqueued an ID directly into Redis without
	// going through the proper creation path, or the row was deleted out
	// from under a live task.
	ErrJobNotFound = errors.New("job execution failed: no processed_jobs row found for taskID")
)

// Job status values stored in processed_jobs.status and workflows.status.
const (
	StatusPending   = "PENDING"
	StatusQueued    = "QUEUED"
	StatusRunning   = "RUNNING"
	StatusCompleted = "COMPLETED"
	StatusFailed    = "FAILED"
	StatusCancelled = "CANCELLED"
)

// Task represents a single unit of work to be created in Postgres before
// its ID is enqueued onto Redis. WorkflowID and ParentIDs model the DAG
// structure: every task belongs to exactly one workflow, and may optionally
// have parent tasks it depends on (must complete before this runs).
type Task struct {
	ID         uuid.UUID
	WorkflowID uuid.UUID
	ParentIDs  []uuid.UUID // empty slice for root tasks in a workflow
	TaskType   string
	Payload    json.RawMessage
	MaxRetries int // 0 means "use the schema default (3)"
}

type JobRepository struct {
	pool *pgxpool.Pool
}

func NewJobRepository(pool *pgxpool.Pool) *JobRepository {
	return &JobRepository{pool: pool}
}

// CreateWorkflow inserts a new workflow row and returns its generated ID.
// Call this once per logical batch of related tasks before creating the
// tasks themselves, since processed_jobs.workflow_id is NOT NULL with a
// foreign key into workflows.
func (r *JobRepository) CreateWorkflow(ctx context.Context, name string) (uuid.UUID, error) {
	var id uuid.UUID
	query := `
		INSERT INTO workflows (name, status)
		VALUES ($1, $2)
		RETURNING id;
	`
	if err := r.pool.QueryRow(ctx, query, name, StatusPending).Scan(&id); err != nil {
		metrics.JobRepoErrors.WithLabelValues("_workflow", "CreateWorkflow").Inc()
		return uuid.Nil, fmt.Errorf("failed to create workflow %q: %w", name, err)
	}
	metrics.WorkflowsCreated.Inc()
	return id, nil
}

// CreateJob inserts a processed_jobs row for the given task, in PENDING
// status, BEFORE the task's ID is enqueued onto Redis. If the task has
// parent dependencies, those are inserted into job_dependencies table.
//
// task.ID is generated by the caller (uuid.New()) rather than by Postgres,
// because the same ID is used as the Redis queue member — Redis and
// Postgres need to agree on task identity before either one sees the task.
func (r *JobRepository) CreateJob(ctx context.Context, queueName string, task Task) error {
	payload := task.Payload
	if payload == nil {
		payload = json.RawMessage(`{}`)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CreateJob").Inc()
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Insert the job
	query := `
		INSERT INTO processed_jobs (id, workflow_id, task_type, status, task_details, max_retries)
		VALUES ($1, $2, $3, $4, $5, COALESCE(NULLIF($6, 0), 3));
	`
	_, err = tx.Exec(ctx, query,
		task.ID, task.WorkflowID, task.TaskType, StatusPending, payload, task.MaxRetries,
	)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CreateJob").Inc()
		return fmt.Errorf("failed to create job %s: %w", task.ID, err)
	}

	// Insert parent dependencies if any
	if len(task.ParentIDs) > 0 {
		depQuery := `
			INSERT INTO job_dependencies (child_job_id, parent_job_id)
			VALUES ($1, $2);
		`
		for _, parentID := range task.ParentIDs {
			_, err = tx.Exec(ctx, depQuery, task.ID, parentID)
			if err != nil {
				metrics.JobRepoErrors.WithLabelValues(queueName, "CreateJob").Inc()
				return fmt.Errorf("failed to create dependency %s -> %s: %w", parentID, task.ID, err)
			}
		}
	}

	if err := tx.Commit(ctx); err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CreateJob").Inc()
		return fmt.Errorf("failed to commit job creation: %w", err)
	}

	return nil
}

// TryStartJob implements the idempotency/ownership layer for job execution.
//
// Unlike an earlier version of this method, this is now UPDATE-only — it
// does not create rows. Every task's processed_jobs row is created up front
// by CreateJob, before the task's ID is ever pushed onto Redis, so by the
// time a worker calls TryStartJob the row is guaranteed to exist. If it
// doesn't, that's a real bug elsewhere (an ID reached Redis without going
// through CreateJob) and is surfaced as ErrJobNotFound rather than silently
// fabricated, which is what the old INSERT ... ON CONFLICT version did
// (and which broke the workflow_id / task_type / task_details columns by
// filling them with placeholder garbage).
//
// Three outcomes for a given taskID's existing row:
//  1. status == COMPLETED -> returns ErrDuplicateJob; caller should drop the task.
//  2. status == PENDING or RUNNING (the common case: fresh task, or one
//     abandoned by a crashed worker and swept back onto the queue by the
//     janitor) -> claimed and moved to RUNNING. Returns (RUNNING, nil).
//  3. no row exists -> returns ErrJobNotFound.
//
// As before, this does not distinguish "abandoned, safe to resume" from
// "actively owned by another worker right now" — see ErrJobAlreadyOwned's
// doc comment for why that's acceptable under this system's current claim
// model (Redis BLMOVE is the sole claim authority).
func (r *JobRepository) TryStartJob(ctx context.Context, queueName, taskID string) (string, error) {
	id, err := uuid.Parse(taskID)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "TryStartJob").Inc()
		return "", fmt.Errorf("taskID %q is not a valid UUID: %w", taskID, err)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "TryStartJob").Inc()
		return "", fmt.Errorf("failed to begin idempotency transaction: %w", err)
	}
	defer tx.Rollback(ctx) // no-op if Commit succeeds first

	var currentStatus string
	query := `
		UPDATE processed_jobs
		SET status = CASE
			WHEN status = $2 THEN $2
			ELSE $3
		END
		WHERE id = $1
		RETURNING status;
	`
	err = tx.QueryRow(ctx, query, id, StatusCompleted, StatusRunning).Scan(&currentStatus)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			metrics.JobRepoErrors.WithLabelValues(queueName, "TryStartJob").Inc()
			return "", ErrJobNotFound
		}
		metrics.JobRepoErrors.WithLabelValues(queueName, "TryStartJob").Inc()
		return "", fmt.Errorf("failed to execute idempotency transaction check: %w", err)
	}

	if currentStatus == StatusCompleted {
		// Rolls back via defer — no mutation should persist for a duplicate.
		metrics.JobsDuplicateSkipped.WithLabelValues(queueName).Inc()
		return "", ErrDuplicateJob
	}

	slog.Info("[IDEMPOTENCY] job claimed", "taskId", taskID, "status", currentStatus)

	if err := tx.Commit(ctx); err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "TryStartJob").Inc()
		return "", fmt.Errorf("failed to commit idempotency transaction: %w", err)
	}

	return currentStatus, nil
}

func (r *JobRepository) CompleteJob(ctx context.Context, queueName, taskID string) error {
	id, err := uuid.Parse(taskID)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CompleteJob").Inc()
		return fmt.Errorf("taskID %q is not a valid UUID: %w", taskID, err)
	}

	query := `
		UPDATE processed_jobs
		SET status = $2,
		    processed_at = NOW()
		WHERE id = $1;
	`
	tag, err := r.pool.Exec(ctx, query, id, StatusCompleted)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CompleteJob").Inc()
		return fmt.Errorf("failed to mark job as completed: %w", err)
	}
	if tag.RowsAffected() == 0 {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CompleteJob").Inc()
		return fmt.Errorf("failed to mark job as completed: %w: %s", ErrJobNotFound, taskID)
	}
	metrics.JobsCompleted.WithLabelValues(queueName).Inc()
	return nil
}

// RecordFailure increments the retry counter and stores the latest error,
// transitioning status to FAILED once max_retries is reached. Returns the
// updated (currentRetries, maxRetries) so the caller can decide retry vs DLQ.
func (r *JobRepository) RecordFailure(ctx context.Context, queueName, taskID, errLog string) (currentRetries int, maxRetries int, err error) {
	id, parseErr := uuid.Parse(taskID)
	if parseErr != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "RecordFailure").Inc()
		return 0, 0, fmt.Errorf("taskID %q is not a valid UUID: %w", taskID, parseErr)
	}

	query := `
		UPDATE processed_jobs
		SET current_retries = current_retries + 1,
		    error_log = $2,
		    status = CASE
		    	WHEN current_retries + 1 >= max_retries THEN $3
		    	ELSE $4
		    END
		WHERE id = $1
		RETURNING current_retries, max_retries;
	`
	err = r.pool.QueryRow(ctx, query, id, errLog, StatusFailed, StatusPending).Scan(&currentRetries, &maxRetries)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "RecordFailure").Inc()
		return 0, 0, fmt.Errorf("failed to record failure for task %s: %w", taskID, err)
	}
	if currentRetries >= maxRetries {
		metrics.JobsFailedTerminal.WithLabelValues(queueName).Inc()
	}
	return currentRetries, maxRetries, nil
}

// CheckAndEnqueueChildren checks if all parents of potential children are
// COMPLETED, and if so, returns a list of child task IDs ready to be enqueued.
// Call this after successfully completing a job to trigger dependent tasks.
func (r *JobRepository) CheckAndEnqueueChildren(ctx context.Context, queueName, completedTaskID string) ([]string, error) {
	id, err := uuid.Parse(completedTaskID)
	if err != nil {
		return nil, fmt.Errorf("taskID %q is not a valid UUID: %w", completedTaskID, err)
	}

	// Find all children of this task where ALL parents are COMPLETED
	query := `
		SELECT DISTINCT jd.child_job_id
		FROM job_dependencies jd
		WHERE jd.parent_job_id = $1
		  AND NOT EXISTS (
			  -- Child is ready only if ALL its parents are COMPLETED
			  SELECT 1
			  FROM job_dependencies jd2
			  INNER JOIN processed_jobs pj ON jd2.parent_job_id = pj.id
			  WHERE jd2.child_job_id = jd.child_job_id
			    AND pj.status != $2
		  );
	`

	rows, err := r.pool.Query(ctx, query, id, StatusCompleted)
	if err != nil {
		metrics.JobRepoErrors.WithLabelValues(queueName, "CheckAndEnqueueChildren").Inc()
		return nil, fmt.Errorf("failed to query ready children: %w", err)
	}
	defer rows.Close()

	var readyChildren []string
	for rows.Next() {
		var childID uuid.UUID
		if err := rows.Scan(&childID); err != nil {
			return nil, fmt.Errorf("failed to scan child ID: %w", err)
		}
		readyChildren = append(readyChildren, childID.String())
	}

	return readyChildren, rows.Err()
}
